Integración Firebase
PracticaDS/s1-2020-tp-grupo2 pull request #14
Opened 2020-05-02 15:10 UTC by rozaracho

- Se agrega configuración de Firebase, integrando Google Analytics y Crashlytics. 
- Se agregan primeros eventos para Google Analytics.

2020-05-06 23:43 UTC, AlvarezAriel requested changes

2020-05-06 23:43 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_create/PostCreateFragment.kt
> +            viewModel.createPost() }
Las analíticas serían parte del dominio, en teoría el loggeo debería estar en el ViewModel.
Por ahora en el viewmodel pueden injectar el context (con poner `val context:Context` en el constructor del viewmodel alcanza) y simplemente llamar a `logEventSavePost(context)` dentro de `fun createPost()`.

Pero como no está bueno abusar de ese context (por razones que son un poco largas para este comentario), en un futuro si quieren hacer un refactor pueden injectar una clase `AnalyticsLogger` o algo así, que encapsule a firebase y ya tenga injectado un context. Sino lo que les va a pasar es que les va a costar mockear los logs y los tests de integración les van a ensuciar el historial de eventos en firebase.

2020-05-09 00:07 UTC, rozaracho commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_create/PostCreateFragment.kt
> +            viewModel.createPost() }
@AlvarezAriel hicimos la corrección que nos pediste, por ahora lo pusimos en el viewModel pero ni bien lo podamos meger  el branch a development, vamos a trabajar en el refactor.

2020-05-09 00:28 UTC, AlvarezAriel approved these changes
Genial, aprobado!

2020-05-09 00:56 UTC, merged