Refactor del log de eventos de Firebase Analytics
PracticaDS/s1-2020-tp-grupo2 pull request #15
Opened 2020-05-10 20:49 UTC by ingridc

Buenas, según los comentarios que nos hizo Ariel, incorporamos un refactor del log de eventos donde inyectamos en los view models la clase AnalyticsLogger, la cual tiene inyectada el Context.

Cualquier comentario estamos a disposición.

Saludos!

2020-05-10 22:13 UTC, AlvarezAriel approved these changes
El cambio está ok como refactor. Tengo una duda nomás respecto de algo que no estoy viendo, que es en qué momento se hace el provides del AnalyticsLogger. O sea, cómo sabe Dagger cómo construir esa instancia.

Después hay un tema ya más fino que es pensar si está bueno o no hacer un método por cada evento. Por ahí sería mejor definir constantes (que pueden ser objects, enums, etc) para cada evento. 

Digo esto porque la ventaja de inyectar esta clase es después poder mockearla, y para eso es más práctico tener definida una interfaz e inyectar eso. 
Porque si por cada vez que se agrega un evento hay que escribir el método por duplicado en la interfaz y en la implementación es medio un garrón. Y si a eso le sumamos que por ahí queremos otro logger distinto en debug (por ejemplo, uno que solamente imprima por consola), ahí implicaría mantener un montón de firmas en 3 lugares.

Pero eso, como primer approach de refactor está bien. Nomás si pueden respóndanme la pregunta que hice al principio.

2020-05-13 19:45 UTC, rozaracho commented
Buenas Ari, nos habíamos olvidado de agregar el provides de AnalyticsLogger y mejoramos el envió de los eventos.

2020-05-13 19:57 UTC, AlvarezAriel requested changes

2020-05-13 19:57 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/logger/TypeEventAnalytics.kt
> +}
Acá conviene explicitar el nombre del evento con un string, porque si la app se ofusca el value del enum puede variar:

```
enum class TypeEventAnalytics(val eventName:String) {     
    CREATE_NEW_POST("CREATE_NEW_POST"),     
    EDIT_POST("EDIT_POST"),     
    DELETE_POST("DELETE_POST"),     
    CANCEL_EDIT_POST("CANCEL_EDIT_POST"),     
    VIEW_POST("VIEW_POST")   
}
```
Y usar ese `eventName` en lugar del `toString()`

2020-05-13 20:12 UTC, AlvarezAriel approved these changes

2020-05-13 21:36 UTC, merged