Cambio el ícono de la app
PracticaDS/s1-2020-tp-grupo2 pull request #8
Opened 2020-04-22 00:26 UTC by ingridc

2020-04-22 03:14 UTC, AugustoConti requested changes
Hola @ingridc, esta muy bueno el ícono!
Creo que faltan los íconos redondos, que están en las mismas carpetas que los que agregaste.
Justo yo tengo los redondos, asique cuando lo probe no lo veía.

2020-04-22 16:41 UTC, ingridc commented
> Hola @ingridc, esta muy bueno el ícono!
> Creo que faltan los íconos redondos, que están en las mismas carpetas que los que agregaste.
> Justo yo tengo los redondos, asique cuando lo probe no lo veía.

Tenés razón @AugustoConti 
Ya los subí :)

2020-04-22 21:24 UTC, lucianoamoruso approved these changes
si

2020-04-23 00:38 UTC, AugustoConti approved these changes

2020-04-23 00:39 UTC, merged