Requested features
PracticaDS/s1-2020-tp-grupo2 pull request #9
Opened 2020-04-22 03:03 UTC by AugustoConti

Hola! :hand: 

Si, ya se que son demasiadas cosas para un solo PR :man_facepalming: 
Se nos fue la mano, no va a volver a ocurrir :stuck_out_tongue_closed_eyes: 

- Funcionalidades:
	- Editar post
	- Eliminar post
	- Empty state
- Refactor en los test, para que sean mas legibles.

2020-04-22 08:21 UTC, AlvarezAriel requested changes

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/data/database.kt
> +    var bodyPath: String? = null,
Cuál fue la motivación para usar `var` en lugar de `val` en estas entidades?

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_create/PostCreateFragment.kt
> +class PostCreateFragment : BaseFragment(R.layout.fragment_post_edit) {
:+1: que hayan pasado el layout en el constructor, queda mejor.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_detail/PostDetailFragment.kt
> +                .setAction(R.string.undo) { viewModel.cancelDeletePost() }
Excelente que se de la opción de undo.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_detail/PostDetailViewModel.kt
> +        blogEntriesRepository.updateBlogEntry(aPost).blockingAwait()
Jamás se debe bloquear el UI thread, esto debería correr en un backgroun thread. Si llega a tomar más tiempo de la cuenta, puede desde droppear frames hasta causar un ANR (https://developer.android.com/topic/performance/vitals/anr)

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_detail/PostDetailViewModel.kt
> +        blogEntriesRepository.updateBlogEntry(aPost).blockingAwait()
Mismo problema que en el otro método. No se debe bloquear el main thread.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_edit/PostEditFragment.kt
> +            Aztec.with(body, source, formatting_toolbar, object : IAztecToolbarClickListener {
Este listener vacío se está usando en dos lados. Se podría extraer esta clase anónima a otra parte o implementarla en una open class con métodos vacíos.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_edit/PostEditViewModel.kt
> +            blogEntriesRepository.updateBlogEntry(post.value!!).blockingAwait()
Este subscribe va a ejecutarse en el main thread, así que no debería bloquearse.
Para este caso se puede usar `flatMap` de la siguiente manera:
```
.flatMapCompletable { blogEntriesRepository.updateBlogEntry(post.value!!) }
.subscribe {
    state.value = State.SUCCESS
}

```

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_edit/PostEditViewModel.kt
> +    var post = MutableLiveData<BlogEntry?>()
Se puede usar val en este caso, en ningún momento se reasigna post.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_edit/PostEditViewModel.kt
> +        }
No le termino de ver la ventaja a `updateField`.

Por un lado el field no necesita ser mutable, además con un data class como estaba antes se puede hacer algo como:

```
fun updateColor(newColor: Int) {
    post.value = post.value?.copy(color = newColor)
}
```
Que termina siendo más corto y más legible.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/posts_listing/PostsListingFragment.kt
> +            layout_empty.visibility = if (postList.isEmpty()) View.VISIBLE else View.INVISIBLE
trivial: Kotlin provee un extension method para este caso, se puede escribir:
```
layout_empty.isInvisible = postList.isNotEmpty()
```

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/res/drawable/ic_empty_list.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Esta imagen vectorial es bastante compleja, en estos casos es más eficiente utilizar una imagen rasterizada, por ejemplo en formato webp.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/res/layout/fragment_posts_listing.xml
> +    <RelativeLayout
El `RelativeLayout` hoy en día está prácticamente deprecado, y es innecesario si ya se está usando un `ConstraintLayout`.
Acá hay dos opciones, o poner el contenido actual del RelativeLayout directamente dentro del ConstraintLayout, o cambiar al RelativeLayout por un LinearLayout o FrameLayout

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/res/layout/fragment_posts_listing.xml
> +            android:contentDescription="@string/list_background"
En este caso sería preferible usar `@string/text_empty_list`. La idea de este description es que le permite a no videntes escuchar la descripción de la imagen.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/res/values/strings.xml
> +    <string name="list_background">list_background</string>
Este texto se está usando en una propiedad `contentDescription`, debería poder ser pronunciable por las apps de accesibilidad.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_edit/PostEditViewModel.kt
> +                bodyText.value = File(context.filesDir, it.bodyPath!!).readText()
Ese `readText` puede ser costoso, no se deberían leer archivos en el main thread.

2020-04-22 08:21 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_detail/PostDetailFragment.kt
> +                else -> { /* Do nothing, should not happen*/
Técnicamente ese comentario en este caso no es cierto, porque el state puede tomar el valor `VIEW`, con lo cual ese `else` sí se ejecutaría.

2020-04-23 01:14 UTC, lucianoamoruso approved these changes

2020-04-23 03:06 UTC, AugustoConti commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/data/database.kt
> +    var bodyPath: String? = null,
Para modificar esa instancia y no tener que crear otra.
Pero pudiendo hacer copy de la data class queda mejor.

2020-04-23 03:07 UTC, AugustoConti commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_edit/PostEditFragment.kt
> +            Aztec.with(body, source, formatting_toolbar, object : IAztecToolbarClickListener {
Extraído!

2020-04-23 03:11 UTC, AugustoConti commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_edit/PostEditViewModel.kt
> +        }
Si, queda mejor. Ya lo cambiamos.

2020-04-25 20:39 UTC, AugustoConti commented
Hola @AlvarezAriel :hand:!

Ya arreglamos todos los puntos.
Y además extraímos PostService :ok_hand: 

Que opinas?

2020-04-26 01:09 UTC, AlvarezAriel approved these changes
Aprobado! Quedó mucho más prolijo

2020-04-26 01:09 UTC, AlvarezAriel commented on app/src/androidTest/java/ar/edu/unq/pdes/myprivateblog/PostsListingTest.kt
> +        checkPostList_hasText(postTitleEdited)
Me gusta lo fácil que se puede ir leyendo el test

2020-04-26 01:09 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_detail/PostDetailViewModel.kt
> +        val disposable = postService.restore(aPost).subscribe()
Comentario: acá hay algo sutil que yo no vengo haciendo y no les voy a pedir que hagan porque en nuestro contexto no va a afectar mucho, pero que está bueno saber.
Ese disposable es un handler que me permite cancelar una requests antes de que retorne. Entonces, si el usuario estaba haciendo algo y se fue a otra pantalla o canceló una acción, etc. se puede cancelar la acción antes de que termine, para que no use recursos innecesarios. 
Un caso típico es cuando tengo una lista de imágenes a cargar, si la imágen todavía no terminó de cargar pero el usuario ya scrolleó para ver otra cosa de manera tal que la imagen ya no está en el rectángulo visible, se cancela la carga de la imagen, porque ya no tiene sentido estar cargando algo que no se va a llegar a mostrar.
En este caso lo peor que puede pasar es que la acción termine y nadie esté vivo para escuchar el resultado, para ustedes esto no es un problema. En algunos otros casos podría llegar a causar un memory leak. En una app "de verdad" insistiría en limpiar esto. 
Pero se los cuento para que entiendan por qué está ese disposable, no hace falta que lo hagan. O se puede hacer en algún futuro refactor cuando veamos cómo detectar memory leaks :P

2020-04-26 01:09 UTC, AlvarezAriel commented on app/src/main/java/ar/edu/unq/pdes/myprivateblog/screens/post_edit/PostEditViewModel.kt
> +            .subscribe { state.value = State.SUCCESS }
En otro PR pueden hacer manejo de errores

2020-04-26 02:31 UTC, merged